backend:
  name: github
  repo: nspilman/wgp-gridsome

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}